import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/appSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (  
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
           <header className="fixed top-0 left-0 w-full z-50 bg-white/95 backdrop-blur-sm border-b border-slate-200">
            <div className="max-w-[1200px] mx-auto px-6 py-4 flex items-center gap-4">
              {/* logo/name */}
              <div className="flex items-center gap-3">
                <div className="h-9 w-9 bg-primary rounded-md flex items-center justify-center text-white font-semibold">CQ</div>
                <span className="text-lg font-semibold">CampaignIQ</span>
              </div>
              {/* spacer */}
              <div className="flex-1" />
              {/* small helper text */}
              <div className="text-sm text-slate-600">Conta: Empresa Exemplo</div>
            </div>
      </header>
          {children}
        </body>
  
      </html>
  );
}
